# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agentmesh import v2_pb2 as agentmesh_dot_v2__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agentmesh.v2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentMeshControlPlaneStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTask = channel.unary_unary(
                '/agentmesh.v2.AgentMeshControlPlane/SubmitTask',
                request_serializer=agentmesh_dot_v2__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=agentmesh_dot_v2__pb2.SubmitTaskResponse.FromString,
                _registered_method=True)
        self.PollTask = channel.unary_unary(
                '/agentmesh.v2.AgentMeshControlPlane/PollTask',
                request_serializer=agentmesh_dot_v2__pb2.PollTaskRequest.SerializeToString,
                response_deserializer=agentmesh_dot_v2__pb2.PollTaskResponse.FromString,
                _registered_method=True)
        self.SubmitResult = channel.unary_unary(
                '/agentmesh.v2.AgentMeshControlPlane/SubmitResult',
                request_serializer=agentmesh_dot_v2__pb2.SubmitResultRequest.SerializeToString,
                response_deserializer=agentmesh_dot_v2__pb2.SubmitResultResponse.FromString,
                _registered_method=True)
        self.SubmitHITLDecision = channel.unary_unary(
                '/agentmesh.v2.AgentMeshControlPlane/SubmitHITLDecision',
                request_serializer=agentmesh_dot_v2__pb2.HITLDecisionRequest.SerializeToString,
                response_deserializer=agentmesh_dot_v2__pb2.HITLDecisionResponse.FromString,
                _registered_method=True)
        self.StreamTaskEvents = channel.unary_stream(
                '/agentmesh.v2.AgentMeshControlPlane/StreamTaskEvents',
                request_serializer=agentmesh_dot_v2__pb2.StreamTaskEventsRequest.SerializeToString,
                response_deserializer=agentmesh_dot_v2__pb2.TaskEvent.FromString,
                _registered_method=True)


class AgentMeshControlPlaneServicer:
    """Missing associated documentation comment in .proto file."""

    def SubmitTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitHITLDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTaskEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentMeshControlPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=agentmesh_dot_v2__pb2.SubmitTaskRequest.FromString,
                    response_serializer=agentmesh_dot_v2__pb2.SubmitTaskResponse.SerializeToString,
            ),
            'PollTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PollTask,
                    request_deserializer=agentmesh_dot_v2__pb2.PollTaskRequest.FromString,
                    response_serializer=agentmesh_dot_v2__pb2.PollTaskResponse.SerializeToString,
            ),
            'SubmitResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitResult,
                    request_deserializer=agentmesh_dot_v2__pb2.SubmitResultRequest.FromString,
                    response_serializer=agentmesh_dot_v2__pb2.SubmitResultResponse.SerializeToString,
            ),
            'SubmitHITLDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitHITLDecision,
                    request_deserializer=agentmesh_dot_v2__pb2.HITLDecisionRequest.FromString,
                    response_serializer=agentmesh_dot_v2__pb2.HITLDecisionResponse.SerializeToString,
            ),
            'StreamTaskEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTaskEvents,
                    request_deserializer=agentmesh_dot_v2__pb2.StreamTaskEventsRequest.FromString,
                    response_serializer=agentmesh_dot_v2__pb2.TaskEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentmesh.v2.AgentMeshControlPlane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentmesh.v2.AgentMeshControlPlane', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentMeshControlPlane:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmesh.v2.AgentMeshControlPlane/SubmitTask',
            agentmesh_dot_v2__pb2.SubmitTaskRequest.SerializeToString,
            agentmesh_dot_v2__pb2.SubmitTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmesh.v2.AgentMeshControlPlane/PollTask',
            agentmesh_dot_v2__pb2.PollTaskRequest.SerializeToString,
            agentmesh_dot_v2__pb2.PollTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmesh.v2.AgentMeshControlPlane/SubmitResult',
            agentmesh_dot_v2__pb2.SubmitResultRequest.SerializeToString,
            agentmesh_dot_v2__pb2.SubmitResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitHITLDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmesh.v2.AgentMeshControlPlane/SubmitHITLDecision',
            agentmesh_dot_v2__pb2.HITLDecisionRequest.SerializeToString,
            agentmesh_dot_v2__pb2.HITLDecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTaskEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agentmesh.v2.AgentMeshControlPlane/StreamTaskEvents',
            agentmesh_dot_v2__pb2.StreamTaskEventsRequest.SerializeToString,
            agentmesh_dot_v2__pb2.TaskEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
